site_name: "Project Nessie: A Git-Like Experience for your Data Lake"
site_description: "Project Nessie is a cloud native OSS service that works with Apache Iceberg, Hive Tables and Delta Lake tables to give your data lake cross-table transactions and a Git-like experience to data history."
edit_uri: ""
strict: true
remote_name: origin
remote_branch: gh-pages
use_directory_urls: true
#include_search_page: false
#search_index_only: true
theme:
  name: material
  custom_dir: overrides
  logo: img/small.svg
  favicon: images/fav2.png

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
extra_css:
  - stylesheets/extra.css

google_analytics:
  - UA-177850801-1
  - auto
extra:
  versions:
    java: 0.3.0
    python: v0.3.0
    iceberg: 0.11.0
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/projectnessie
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/projectnessie/nessie
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC5xjzYuGGuGPCY9FNtqZMsQ?view_as=subscriber
repo_url: https://github.com/projectnessie/nessie
plugins:
  - markdownextradata
  - search
  - awesome-pages:
      filename: _config
  - minify:
      minify_html: true
markdown_extensions:
  - smarty
  - sane_lists
  - extra
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: projectnessie
      repo: nessie
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
